### ISSUE TITLE
Pip2conda requires pyproject.toml or setup.py 

### ISSUE THREAD

**Issue by minwang-ai** [duncanmmacleod/pip2conda#23]
Hi,

Thank you for your work about the tool!
Pip2conda always requires pyproject.toml or setup.py but the project does not provide these files. By the way, It is common that some research projects do not have these files otherwise we even do not need tools like pip2conda.

Best wishes,
Min

```
Traceback (most recent call last):
  File "/bigpool/homes/minwang/BIND/envs/bin/pip2conda", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/bigpool/homes/minwang/BIND/envs/lib/python3.11/site-packages/pip2conda/pip2conda.py", line 663, in main
    requirements = sorted(pip2conda(
                          ^^^^^^^^^^
  File "/bigpool/homes/minwang/BIND/envs/lib/python3.11/site-packages/pip2conda/pip2conda.py", line 551, in pip2conda
    return filter_requirements(
           ^^^^^^^^^^^^^^^^^^^^
  File "/bigpool/homes/minwang/BIND/envs/lib/python3.11/site-packages/pip2conda/pip2conda.py", line 471, in filter_requirements
    requirements = set(requirements)
                   ^^^^^^^^^^^^^^^^^
  File "/bigpool/homes/minwang/BIND/envs/lib/python3.11/site-packages/pip2conda/pip2conda.py", line 350, in parse_all_requirements
    meta = build_project_metadata(project_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bigpool/homes/minwang/BIND/envs/lib/python3.11/site-packages/pip2conda/pip2conda.py", line 154, in build_project_metadata
    builder = ProjectBuilder(project_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bigpool/homes/minwang/BIND/envs/lib/python3.11/site-packages/build/__init__.py", line 267, in __init__
    _validate_source_directory(srcdir)
  File "/bigpool/homes/minwang/BIND/envs/lib/python3.11/site-packages/build/__init__.py", line 135, in _validate_source_directory
    raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
build.BuildException: Source /bigpool/homes/minwang/BIND/implementations does not appear to be a Python project: no pyproject.toml or setup.py
```

**Comment by duncanmmacleod** [comment]
@minwang-ai, sorry for the delay in reponding. I'm a little confused by the use case, can you give an example project that you would likee to use with pip2conda, but cannot, or please include the full command you are executing that generated the above traceback?

**Comment by ideologysec** [comment]
A lot of pip projects use "requirements.txt": here's one that I found that pip2conda errors out on.

https://github.com/comfyanonymous/ComfyUI/blob/master/requirements.txt

**Comment by duncanmmacleod** [comment]
@ideologysec, thanks for the link. `pip2conda` is designed to work with Python package projects, where my definition of a 'package' is a project that includes a pyproject.toml, or at least something that `pip install .` can understand.

It would probably be a small feature addition to handle non-package projects, where just a requirements.txt file is available. Or, to support passing a `.txt` file directly through a new argument. I'll have a think.

**Comment by duncanmmacleod** [comment]
@ideologysec, I totally forgot that this use case is already supported, you can use the `-r/--requirements-file` command-line option to pass in any number of requirements.txt-format files.

The catch, which is not documented, is that `pip2conda` will still try and parse the `-d/--project` option (which defaults to the current working directory) _first_.

For the ComfyUI project you linked to, I get this:

```console
$ pip2conda -r ./requirements.txt
[2025-01-07 13:59:10]  WARNING: conda failed to find some packages, attempting to parse what's missing
[2025-01-07 13:59:10]  WARNING:   removing 'spandrel'
[2025-01-07 13:59:10]  WARNING:   removing 'soundfile'
aiohttp
einops
kornia>=0.7.1
pillow
psutil
pytorch
pyyaml
safetensors>=0.4.2
scipy
sentencepiece
tokenizers>=0.13.3
torchaudio
torchsde
torchvision
tqdm
transformers>=4.28.1
```

Does that meet your need?

**Comment by ideologysec** [comment]
that's great, thank you! not sure how I missed this.

I think this is okay to close. (maybe add something to the README, since I found this project searching for "how do I turn a pip requirements file into a conda requirements file")
